version: '3'
services:
  roslaunch:
    build: ./
    command: tail -f /dev/null
    volumes: 
      - .:/root/arena_ws/src/arena-rosnav
    environment:
      - DISPLAY=novnc:0.0
    image: arena_rosnav
    networks:
      - x11
    container_name: arena-rosnav
  novnc:  
    image: theasp/novnc:latest
    env_file:
      - ./docker/novnc.env
    ports:
      - "8080:8080"
    networks:
      - x11
    container_name: novnc
networks:
  x11:
